services:
  app:
    image: ghcr.io/tommyne/d3v0n:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.d3v0n.rule=Host(`www.d3v0n.de`) || Host(`d3v0n.de`)"
      - "traefik.http.routers.d3v0n.entrypoints=websecure"
      - "traefik.http.routers.d3v0n.tls.certresolver=le"
      - "traefik.http.routers.d3v0n.priority=100"
      - "traefik.http.routers.d3v0n.service=d3v0n"
      - "traefik.http.services.d3v0n.loadbalancer.server.port=80"
    # zum Debuggen der Unit-Control-API:
    # - "8443:8443"
    networks:
      - web

networks:
    web:
      external: true
