/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechstackRouteImport } from './routes/techstack'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImpressRouteImport } from './routes/impress'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TechstackRoute = TechstackRouteImport.update({
  id: '/techstack',
  path: '/techstack',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressRoute = ImpressRouteImport.update({
  id: '/impress',
  path: '/impress',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/impress': typeof ImpressRoute
  '/privacy': typeof PrivacyRoute
  '/techstack': typeof TechstackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/impress': typeof ImpressRoute
  '/privacy': typeof PrivacyRoute
  '/techstack': typeof TechstackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/impress': typeof ImpressRoute
  '/privacy': typeof PrivacyRoute
  '/techstack': typeof TechstackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/impress'
    | '/privacy'
    | '/techstack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/impress'
    | '/privacy'
    | '/techstack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/impress'
    | '/privacy'
    | '/techstack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ContactRoute: typeof ContactRoute
  ImpressRoute: typeof ImpressRoute
  PrivacyRoute: typeof PrivacyRoute
  TechstackRoute: typeof TechstackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/techstack': {
      id: '/techstack'
      path: '/techstack'
      fullPath: '/techstack'
      preLoaderRoute: typeof TechstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impress': {
      id: '/impress'
      path: '/impress'
      fullPath: '/impress'
      preLoaderRoute: typeof ImpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ContactRoute: ContactRoute,
  ImpressRoute: ImpressRoute,
  PrivacyRoute: PrivacyRoute,
  TechstackRoute: TechstackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
